class Sol
  attr_accessor :name, :dna, :state, :transforms, :traces
  
  # list of spirations autogenerated from filenames in directory of this sol
  # and all supersols
  def initialize name, dna, params={}
    @name, @dna = name, dna
    @breaths = dna[:breath]
    @state = dna[:substrate].new
    @traces = BreathLog.new( self )
    @transforms = dna[:transform].map {|x| x.new( self ) }
    #params.call( @state )
  end
  
  def exhale to, kind, body=""
    breath = Breath.const_get(kind.to_s.camelize).new( to, from=self.name, body )    
    @traces << breath
    Network.transpire to, breath
    integrate
  end

  # Called by Flow (delivering breath)
  def inhale breath 
    @traces << breath
    integrate
  end
  
  def integrate
    transforms.each { |t| t.morph }
  end
  
  def self.I_am
    sol = self.new
    sol.spirations = classes_for(:breath)
    sol.state = Substrate::Base.new
    sol.transforms = classes_for(:transform).map {|x| x.new }
  end
end



